spring.application.name=SpringAI

spring.config.import=optional:file:.env[.properties]


spring.ai.openai.api-key=${OPEN_AI_apikey:disabled}

server.port=8081

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=codellama:latest

spring.ai.google.genai.api-key=${GEMINI_API_KEY:disabled}
spring.ai.google.genai.chat.model=gemini-3.1-flash-lite

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
# logging.level.org.springframework.ai.chat.prompt=debug